# Raising an exception

e = ValueError("not the right value")

raise e
